### ISSUE TITLE
Instructions to migrate from vTigerCRM 6.5 

### ISSUE THREAD

**Issue by euneuber** [berliCRM/berlicrm#134]
I'd like to convert a vTigerCRM 6.5 installation to berliCRM. How can this be done? Do you have any instructions? (maybe a script?)

**Comment by urban-thinking** [comment]
Hiya,

for a vtiger to berliCRM migration we do not provide any migration instructions or automatic migrations scripts but we offer our paid support. Presumably we cannot write any instructions that always work because there are too many vtiger versions out there. It gets even more complicated if a vtiger version migration was been done before and/or there are local modifications on the vtiger installation (what is usually the case). Therefore, it depends on the individual case, how much effort is needed to migrate. In many cases a 3h workload is sufficient ... but ... it depends :-/

**Comment by NicolasGoeddel** [comment]
I just found out about berliCRM and also want to migrate from a vTiger 6.5.0 to berliCRM now. Where do I get that paid support to migrate vTiger for me? And what would it cost?

**Comment by Archibald111** [comment]
you may contact the crm-now GmbH for berliCRM support, see https://www.crm-now.de/kontakt/
